#!/usr/bin/env bash
# Point every app button at this tree, all four at once.
#
#   bash tools/install_operator_entrypoints.sh            # install
#   bash tools/install_operator_entrypoints.sh --check    # are they agreed?
#   bash tools/install_operator_entrypoints.sh --revert    # put the originals back
#
# WHY ALL FOUR AT ONCE
# --------------------
# scripts/ros1_bluetooth_bridge.py runs a fixed allowlist of four home scripts
# (JobRunner.JOBS), one per app button. They were maintained by hand and edited
# one at a time, and on 2026-08-28 they had drifted apart: [로컬 켜기] brought
# up one deploy while [주행 시작] drove another. Nothing in git could see it,
# because none of the four was in git.
#
# This writes all four in one act, as the same three lines into the same
# absolute path, and refuses to leave them half-written. There is no way to
# update one of them.
set -eo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
ENTRY="$SCRIPT_DIR/wheelchair_entry.sh"
TARGET_HOME="${INSTALL_HOME:-$HOME}"
SUFFIX="${BACKUP_SUFFIX:-.pre-wheelchair-entry}"

fail() { echo "ERROR: $*" >&2; exit 1; }

# name in $HOME  ->  wheelchair_entry.sh subcommand
#
# stop_stack.sh is new to $HOME: the bridge has always offered the job and the
# app has always had the button, but no such script existed anywhere, so the
# button was greyed out for every field session and a bring-up in progress had
# no real abort.
JOBS="start_wheelchair_localization.sh:stack-start
go.sh:drive-start
stop.sh:drive-stop
stop_stack.sh:stack-stop"

[ -f "$ENTRY" ] || fail "$ENTRY not found -- run this from the deploy's own tools/"

case "${1:---install}" in
  --check|check)
    exec bash "$ENTRY" check
    ;;

  --revert|revert)
    restored=0
    while IFS=: read -r name _; do
      [ -n "$name" ] || continue
      backup="$TARGET_HOME/$name$SUFFIX"
      if [ -f "$backup" ]; then
        mv -f "$backup" "$TARGET_HOME/$name"
        echo "restored ~/$name"
        restored=$((restored + 1))
      else
        # A wrapper with no backup was created by us out of nothing
        # (stop_stack.sh). Removing it puts the machine back where it was.
        if [ -f "$TARGET_HOME/$name" ] && \
           grep -q 'wheelchair_entry.sh' "$TARGET_HOME/$name"; then
          rm -f "$TARGET_HOME/$name"
          echo "removed  ~/$name (generated, nothing to restore under it)"
          restored=$((restored + 1))
        else
          echo "skipped  ~/$name (no $SUFFIX backup, and not one of ours)"
        fi
      fi
    done <<EOF
$JOBS
EOF
    [ "$restored" -gt 0 ] || fail "nothing to revert"
    echo ""
    echo "The app is back on whatever these scripts were before. Note that"
    echo "[스택 내리기] is dead again if stop_stack.sh was removed."
    exit 0
    ;;

  --install|install|"") ;;
  -h|--help) sed -n '2,7p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  *) fail "unknown option: $1" ;;
esac

# Resolve BEFORE writing anything. If this tree cannot say what it would run --
# a workspace symlink into another deploy, a missing ws/ -- then installing
# wrappers that point at it just moves the failure to the moment the chair is
# asked to drive.
echo "checking what this tree would actually run..."
bash "$ENTRY" resolve || fail "this deploy does not resolve; not installing wrappers that point at it"
echo ""

# Write to a staging area first and move into place at the end. A wrapper set
# that is half old and half new is the exact failure this script exists to end,
# so it must not be reachable even by interrupting the install.
STAGE="$(mktemp -d "${TMPDIR:-/tmp}/wheelchair-entry.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT

while IFS=: read -r name command; do
  [ -n "$name" ] || continue
  cat > "$STAGE/$name" <<EOF
#!/usr/bin/env bash
# GENERATED by tools/install_operator_entrypoints.sh -- do not edit by hand.
#
# The Bluetooth bridge runs this file when the app's button is pressed. It is
# three lines so that it cannot develop opinions of its own: every decision --
# which deploy, which workspace, which BASE_* -- is made once, in the file
# below, and shared by all four buttons.
#
# installed: $(date -u '+%Y-%m-%dT%H:%M:%SZ') from $SCRIPT_DIR
# check:     bash "$ENTRY" check
exec bash "$ENTRY" $command "\$@"
EOF
  chmod +x "$STAGE/$name"
done <<EOF
$JOBS
EOF

installed=0
while IFS=: read -r name _; do
  [ -n "$name" ] || continue
  live="$TARGET_HOME/$name"
  backup="$live$SUFFIX"
  if [ -f "$live" ] && ! grep -q 'wheelchair_entry.sh' "$live"; then
    # Only ever back up a HAND-WRITTEN script. Backing up one of our own
    # generated wrappers would overwrite the real original the second time
    # this is run, and --revert would then restore a wrapper.
    if [ -f "$backup" ]; then
      echo "note: $backup already exists; leaving the older original in place" >&2
    else
      cp -p "$live" "$backup"
      echo "backed up ~/$name -> ~/$name$SUFFIX"
    fi
  fi
  mv -f "$STAGE/$name" "$live"
  installed=$((installed + 1))
done <<EOF
$JOBS
EOF

echo ""
echo "installed $installed wrappers into $TARGET_HOME"
echo ""
bash "$ENTRY" check
echo ""
echo "Restart the bridge so it re-checks which jobs exist:"
echo "  systemctl --user restart wheelchair-bt-bridge"
